clients:
- url: http://loki:3100/loki/api/v1/push
positions:
  filename: /tmp/positions.yaml
scrape_configs:
- job_name: ai-agent-logs
  static_configs:
  - labels:
      __path__: /home/app/logs/*.log
      host: ai-agent-container
      job: ai-agent
    targets:
    - localhost
- job_name: system-logs
  static_configs:
  - labels:
      __path__: /var/log/*.log
      host: ai-agent-container
      job: system
    targets:
    - localhost
server:
  grpc_listen_port: 0
  http_listen_port: 9080
